schemaVersion: 2.0
timeout: 150

notify:
  pullRequestComment:
    postOnSuccess: false

machine:
  env:
    RUNTIME_JDK_VERSION: 17
    skipTest: false
    CODE_VERSION: $(./code_version.sh)

reports:
  checkstyle: true
  pmd: true
  findbugs: true
  junit: true

jenkins: &jenkins_config
  concurrentBuild: true
  maxConcurrentTotal: 8

pipelines:

# prb builds
- name: apple-1.5.0.x-scala-2.12-prb
  branchName: apple-1.5.0.x
  build:
    template: buildozer:v4:prb
  machine:
    baseImage: docker.apple.com/pie/comet-builder-ubi8:latest
  jenkins: *jenkins_config

- name: apple-1.5.0.x-scala-2.13-prb
  branchName: apple-1.5.0.x
  build:
    template: freestyle:v4:prb
    steps:
      - ./gradlew -DscalaVersion=2.13 :iceberg-spark:iceberg-spark-3.4_2.13:build :iceberg-spark:iceberg-spark-extensions-3.4_2.13:build :iceberg-spark:iceberg-spark-runtime-3.4_2.13:build
  machine:
    baseImage: docker.apple.com/pie/comet-builder-ubi8:latest
  jenkins: *jenkins_config

- name: apple-1.5.0.x-release-scala-2.12-prb
  branchName: apple-1.5.0.x-release
  build:
    template: buildozer:v4:prb
  machine:
    baseImage: docker.apple.com/pie/comet-builder-ubi8:latest
  jenkins: *jenkins_config

- name: apple-1.5.0.x-release-scala-2.13-prb
  branchName: apple-1.5.0.x-release
  build:
    template: freestyle:v4:prb
    steps:
      - ./gradlew -DscalaVersion=2.13 :iceberg-spark:iceberg-spark-3.4_2.13:build :iceberg-spark:iceberg-spark-extensions-3.4_2.13:build :iceberg-spark:iceberg-spark-runtime-3.4_2.13:build
  machine:
    baseImage: docker.apple.com/pie/comet-builder-ubi8:latest
  jenkins: *jenkins_config

# publish pipelines
- name: apple-1.5.0.x-scala-2.12-snapshot
  branchName: apple-1.5.0.x
  build:
    template: buildozer:v4:publish
  package:
    libraries:
    - publish:
      - repo: m2:oss-patched
  finally:
    radar:
      annotate: true
  machine:
    baseImage: docker.apple.com/pie/comet-builder-ubi8:latest
  jenkins: *jenkins_config

- name: apple-1.5.0.x-scala-2.13-snapshot
  branchName: apple-1.5.0.x
  build:
    template: freestyle:v4:publish
    steps:
      - ./gradlew -DscalaVersion=2.13 :iceberg-spark:iceberg-spark-3.4_2.13:build :iceberg-spark:iceberg-spark-extensions-3.4_2.13:build :iceberg-spark:iceberg-spark-runtime-3.4_2.13:build
      - home_dir=$(pwd)
      - ./gradlew -DscalaVersion=2.13 -Dmaven.repo.local=${home_dir}/local-repo :iceberg-spark:iceberg-spark-3.4_2.13:publishToMavenLocal :iceberg-spark:iceberg-spark-extensions-3.4_2.13:publishToMavenLocal :iceberg-spark:iceberg-spark-runtime-3.4_2.13:publishToMavenLocal
      - ci stage-lib --many-many-artifacts "./local-repo/**/*.jar"
      - ci stage-lib --many-many-artifacts "./local-repo/**/*.pom"
  package:
    freeform:
    - publish:
      - repo: m2:oss-patched
  finally:
    radar:
      annotate: true
  machine:
    baseImage: docker.apple.com/pie/comet-builder-ubi8:latest
  jenkins: *jenkins_config

- name: apple-1.5.0.x-scala-2.12-release
  branchName: apple-1.5.0.x-release
  build:
    template: buildozer:v4:publish
  package:
    release: true
    libraries:
    - publish:
      - repo: m2:oss-patched
  finally:
    radar:
      annotate: true
    tag:
      expression: ${CODE_VERSION}
  machine:
    baseImage: docker.apple.com/pie/comet-builder-ubi8:latest
  jenkins: *jenkins_config

- name: apple-1.5.0.x-scala-2.13-release
  branchName: apple-1.5.0.x-release
  build:
    template: freestyle:v4:publish
    steps:
      - ./gradlew -DscalaVersion=2.13 :iceberg-spark:iceberg-spark-3.4_2.13:build :iceberg-spark:iceberg-spark-extensions-3.4_2.13:build :iceberg-spark:iceberg-spark-runtime-3.4_2.13:build
      - home_dir=$(pwd)
      - ./gradlew -Priorelease -DscalaVersion=2.13 -Dmaven.repo.local=${home_dir}/local-repo :iceberg-spark:iceberg-spark-3.4_2.13:publishToMavenLocal :iceberg-spark:iceberg-spark-extensions-3.4_2.13:publishToMavenLocal :iceberg-spark:iceberg-spark-runtime-3.4_2.13:publishToMavenLocal
      - ci stage-lib --many-many-artifacts "./local-repo/**/*.jar"
      - ci stage-lib --many-many-artifacts "./local-repo/**/*.pom"
  package:
    release: true
    freeform:
      - publish:
          - repo: m2:oss-patched
  finally:
    radar:
      annotate: true
  machine:
    baseImage: docker.apple.com/pie/comet-builder-ubi8:latest
  jenkins: *jenkins_config
  